# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: 'mysql-docker'
    ports:
      - 3306:3306
    volumes:
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: nest
volumes:
  db-data:
